### PR TITLE
R pi zero pics working and tested.

### PR DESCRIPTION
**Pull request by JamesCordell**
Hi 

I will start with, this project is amazingly cool and works incredibly well!

I did start by wiring my TX up like the fist image in the wiki. This however did not work well. Once i had read the instructions thoroughly I powered the pi zero by the pins. I tested this for at least 4 hours stright, with no issues.

I have added some pics of my wiring. I also added a capacitor (1000uf 16v) which reduced the hissing noise give by the pi zero stabilizing the power supply which can be easily sourced on popular auction sites.

IMG_20180626_221032.jpg

### CODE REVIEW

**Comment by rodizio1** [comment]
Hmm, I clicked merge, but the pics don't show up?

**Comment by JamesCordell** [comment]
They are there under wiki-content. All seems good.

**Comment by rodizio1** [comment]
Ahh, now I see them. I'll add them to the wiring page later.

The wiring in the first pic (i.e. using the bottom pads near the micro usb socket) works well for me and others though, not sure why it doesn't for you.

Regarding the noise you heard: Did that really come from the Pi Zero? I have never noticed that. 

The 036nha makes a noise, to me it sounds like a clicking noise, dependent on datarate, i.e. if you cover the cam (which reduces datarate and number of injected packets) the clicking gets 'slower'

**Comment by JamesCordell** [comment]
I almost sure it cam from the pi. I suspect the bypass capacitors were being strained due to the noisy voltage regulator i was using. However, once adding that cap 1000uf 16v it disappeared.

**Pull request merged**
