### PR TITLE
mAh in OSD

### PR DESCRIPTION
**Pull request by cyrilknops**
the files on github are not up to date with the files in the 1.6 rc6 image so had to add current_ts() object which is included in the 1.6 rc6 release image

### CODE REVIEW

**Comment by bortek** [comment]
Interesting. I started reviewing the code and finding some discrepancies. 1.6RC6 image, which I downloaded from the Gdrive link on Wiki, only has parts of the code that is in this PR. For example the variable mAhDrawRaw is not there at all (in the image) but present in the Git. Are you using the same 1.6RC6 ? 

I am attaching render.c and render.h which I extracted from 1.6RC6 image. Take a look at them. 

https://ufile.io/krmag
https://ufile.io/0alk0

**Comment by cyrilknops** [comment]
MahDrawnRaw is part of my code for the implementation of the mAh in OSD feature, so it's understandable that it is not included in the image, I was talking about the current-ts() object, there is still some missing code in other files like the gpio-conifg.py for example

**Comment by bortek** [comment]
That explains it :) I am in the process of updating the codebase using one of the 1.6RC6 images and as soon as that is done I will come back here and review/Merge the PR.

**Comment by cyrilknops** [comment]
great to hear, looking forward to pull from a up to date codebase, have a lot of ideas for future features

**Comment by Yes21** [comment]
This Pull Request will have to be merged with this [one](https://github.com/bortek/EZ-WifiBroadcast/pull/160), before 1.7 integration.
Thanks

**Comment by Yes21** [comment]
@bortek Do you know if there's a way to transfer this PR on @RespawnDespair's github ?

**Comment by bortek** [comment]
No there is no way. Prs cannot be transfered. But it's quite easy to create a new one and then close this one. @cyrilknops could you be able to do it?

**Comment by cyrilknops** [comment]
Yes i think so, Will take a look this evening

**Comment by Yes21** [comment]
Yes, I'll do it.
Thanks.

**Pull request merged**
